---
repos:
  # pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: forbid-binary
      - id: go-fmt
      - id: go-mod-tidy
        language: system
        entry: bash -c 'cd backend && exec go mod tidy'
        pass_filenames: false
        types: [ go ]
        files: ^backend/
      - id: go-generate
        language: system
        entry: bash -c 'cd backend && exec go generate'
        pass_filenames: false
        types: [ go ]
        files: ^backend/
    # prepare-commit-msg
  - repo: https://github.com/avilaton/add-msg-issue-prefix-hook
    rev: v0.0.6    # Use the ref you want to point at
    hooks:
      - id: add-msg-issue-prefix
