services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

#  api:
#    build: ./backend
#    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
#    volumes:
#      - ./backend:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#  ui:
#    build: ./frontend
#    command: ["npm", "start"]
#    volumes:
#      - ./frontend:/code
#      - /code/node_modules
#    ports:
#      - "3000:3000"
#    depends_on:
#      - api

volumes:
  pgdata:
