// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: communications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationParticipant = `-- name: AddConversationParticipant :one
INSERT INTO conversation_participants (conversation_id, user_id, character_id)
VALUES ($1, $2, $3)
ON CONFLICT (conversation_id, user_id, character_id) DO NOTHING
RETURNING id, conversation_id, user_id, character_id, joined_at, last_read_at
`

type AddConversationParticipantParams struct {
	ConversationID int32
	UserID         int32
	CharacterID    pgtype.Int4
}

func (q *Queries) AddConversationParticipant(ctx context.Context, arg AddConversationParticipantParams) (ConversationParticipant, error) {
	row := q.db.QueryRow(ctx, addConversationParticipant, arg.ConversationID, arg.UserID, arg.CharacterID)
	var i ConversationParticipant
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.CharacterID,
		&i.JoinedAt,
		&i.LastReadAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (game_id, conversation_type, title, created_by_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, conversation_type, title, created_by_user_id, created_at, updated_at
`

type CreateConversationParams struct {
	GameID           int32
	ConversationType string
	Title            pgtype.Text
	CreatedByUserID  int32
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.GameID,
		arg.ConversationType,
		arg.Title,
		arg.CreatedByUserID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.ConversationType,
		&i.Title,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
INSERT INTO threads (game_id, phase_id, created_by_user_id, title, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, game_id, phase_id, created_by_user_id, title, content, is_pinned, created_at, updated_at
`

type CreateThreadParams struct {
	GameID          int32
	PhaseID         pgtype.Int4
	CreatedByUserID int32
	Title           string
	Content         string
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.GameID,
		arg.PhaseID,
		arg.CreatedByUserID,
		arg.Title,
		arg.Content,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createThreadPost = `-- name: CreateThreadPost :one
INSERT INTO thread_posts (thread_id, parent_post_id, user_id, character_id, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, thread_id, parent_post_id, user_id, character_id, content, is_edited, created_at, updated_at
`

type CreateThreadPostParams struct {
	ThreadID     int32
	ParentPostID pgtype.Int4
	UserID       int32
	CharacterID  pgtype.Int4
	Content      string
}

func (q *Queries) CreateThreadPost(ctx context.Context, arg CreateThreadPostParams) (ThreadPost, error) {
	row := q.db.QueryRow(ctx, createThreadPost,
		arg.ThreadID,
		arg.ParentPostID,
		arg.UserID,
		arg.CharacterID,
		arg.Content,
	)
	var i ThreadPost
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ParentPostID,
		&i.UserID,
		&i.CharacterID,
		&i.Content,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteThread = `-- name: DeleteThread :exec
DELETE FROM threads WHERE id = $1
`

func (q *Queries) DeleteThread(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteThread, id)
	return err
}

const deleteThreadPost = `-- name: DeleteThreadPost :exec
DELETE FROM thread_posts WHERE id = $1
`

func (q *Queries) DeleteThreadPost(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteThreadPost, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, game_id, conversation_type, title, created_by_user_id, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id int32) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.ConversationType,
		&i.Title,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationMessages = `-- name: GetConversationMessages :many
SELECT pm.id, pm.conversation_id, pm.sender_user_id, pm.sender_character_id, pm.content, pm.created_at, pm.updated_at, u.username as sender_username, c.name as sender_character_name
FROM private_messages pm
JOIN users u ON pm.sender_user_id = u.id
LEFT JOIN characters c ON pm.sender_character_id = c.id
WHERE pm.conversation_id = $1
ORDER BY pm.created_at
`

type GetConversationMessagesRow struct {
	ID                  int32
	ConversationID      int32
	SenderUserID        int32
	SenderCharacterID   pgtype.Int4
	Content             string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	SenderUsername      string
	SenderCharacterName pgtype.Text
}

func (q *Queries) GetConversationMessages(ctx context.Context, conversationID int32) ([]GetConversationMessagesRow, error) {
	rows, err := q.db.Query(ctx, getConversationMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationMessagesRow
	for rows.Next() {
		var i GetConversationMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderUserID,
			&i.SenderCharacterID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SenderUsername,
			&i.SenderCharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationParticipants = `-- name: GetConversationParticipants :many
SELECT cp.id, cp.conversation_id, cp.user_id, cp.character_id, cp.joined_at, cp.last_read_at, u.username, c.name as character_name
FROM conversation_participants cp
JOIN users u ON cp.user_id = u.id
LEFT JOIN characters c ON cp.character_id = c.id
WHERE cp.conversation_id = $1
ORDER BY cp.joined_at
`

type GetConversationParticipantsRow struct {
	ID             int32
	ConversationID int32
	UserID         int32
	CharacterID    pgtype.Int4
	JoinedAt       pgtype.Timestamptz
	LastReadAt     pgtype.Timestamptz
	Username       string
	CharacterName  pgtype.Text
}

func (q *Queries) GetConversationParticipants(ctx context.Context, conversationID int32) ([]GetConversationParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getConversationParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationParticipantsRow
	for rows.Next() {
		var i GetConversationParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.CharacterID,
			&i.JoinedAt,
			&i.LastReadAt,
			&i.Username,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameThreads = `-- name: GetGameThreads :many
SELECT t.id, t.game_id, t.phase_id, t.created_by_user_id, t.title, t.content, t.is_pinned, t.created_at, t.updated_at, u.username as creator_username,
       (SELECT COUNT(*) FROM thread_posts WHERE thread_id = t.id) as post_count
FROM threads t
JOIN users u ON t.created_by_user_id = u.id
WHERE t.game_id = $1
ORDER BY t.is_pinned DESC, t.updated_at DESC
`

type GetGameThreadsRow struct {
	ID              int32
	GameID          int32
	PhaseID         pgtype.Int4
	CreatedByUserID int32
	Title           string
	Content         string
	IsPinned        pgtype.Bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CreatorUsername string
	PostCount       int64
}

func (q *Queries) GetGameThreads(ctx context.Context, gameID int32) ([]GetGameThreadsRow, error) {
	rows, err := q.db.Query(ctx, getGameThreads, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameThreadsRow
	for rows.Next() {
		var i GetGameThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.CreatedByUserID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorUsername,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhaseThreads = `-- name: GetPhaseThreads :many
SELECT t.id, t.game_id, t.phase_id, t.created_by_user_id, t.title, t.content, t.is_pinned, t.created_at, t.updated_at, u.username as creator_username,
       (SELECT COUNT(*) FROM thread_posts WHERE thread_id = t.id) as post_count
FROM threads t
JOIN users u ON t.created_by_user_id = u.id
WHERE t.phase_id = $1
ORDER BY t.is_pinned DESC, t.updated_at DESC
`

type GetPhaseThreadsRow struct {
	ID              int32
	GameID          int32
	PhaseID         pgtype.Int4
	CreatedByUserID int32
	Title           string
	Content         string
	IsPinned        pgtype.Bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CreatorUsername string
	PostCount       int64
}

func (q *Queries) GetPhaseThreads(ctx context.Context, phaseID pgtype.Int4) ([]GetPhaseThreadsRow, error) {
	rows, err := q.db.Query(ctx, getPhaseThreads, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhaseThreadsRow
	for rows.Next() {
		var i GetPhaseThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.CreatedByUserID,
			&i.Title,
			&i.Content,
			&i.IsPinned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorUsername,
			&i.PostCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThread = `-- name: GetThread :one
SELECT t.id, t.game_id, t.phase_id, t.created_by_user_id, t.title, t.content, t.is_pinned, t.created_at, t.updated_at, u.username as creator_username
FROM threads t
JOIN users u ON t.created_by_user_id = u.id
WHERE t.id = $1
`

type GetThreadRow struct {
	ID              int32
	GameID          int32
	PhaseID         pgtype.Int4
	CreatedByUserID int32
	Title           string
	Content         string
	IsPinned        pgtype.Bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CreatorUsername string
}

func (q *Queries) GetThread(ctx context.Context, id int32) (GetThreadRow, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i GetThreadRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorUsername,
	)
	return i, err
}

const getThreadPost = `-- name: GetThreadPost :one
SELECT tp.id, tp.thread_id, tp.parent_post_id, tp.user_id, tp.character_id, tp.content, tp.is_edited, tp.created_at, tp.updated_at, u.username, c.name as character_name
FROM thread_posts tp
JOIN users u ON tp.user_id = u.id
LEFT JOIN characters c ON tp.character_id = c.id
WHERE tp.id = $1
`

type GetThreadPostRow struct {
	ID            int32
	ThreadID      int32
	ParentPostID  pgtype.Int4
	UserID        int32
	CharacterID   pgtype.Int4
	Content       string
	IsEdited      pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Username      string
	CharacterName pgtype.Text
}

func (q *Queries) GetThreadPost(ctx context.Context, id int32) (GetThreadPostRow, error) {
	row := q.db.QueryRow(ctx, getThreadPost, id)
	var i GetThreadPostRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ParentPostID,
		&i.UserID,
		&i.CharacterID,
		&i.Content,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.CharacterName,
	)
	return i, err
}

const getThreadPosts = `-- name: GetThreadPosts :many
SELECT tp.id, tp.thread_id, tp.parent_post_id, tp.user_id, tp.character_id, tp.content, tp.is_edited, tp.created_at, tp.updated_at, u.username, c.name as character_name
FROM thread_posts tp
JOIN users u ON tp.user_id = u.id
LEFT JOIN characters c ON tp.character_id = c.id
WHERE tp.thread_id = $1
ORDER BY tp.created_at
`

type GetThreadPostsRow struct {
	ID            int32
	ThreadID      int32
	ParentPostID  pgtype.Int4
	UserID        int32
	CharacterID   pgtype.Int4
	Content       string
	IsEdited      pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Username      string
	CharacterName pgtype.Text
}

func (q *Queries) GetThreadPosts(ctx context.Context, threadID int32) ([]GetThreadPostsRow, error) {
	rows, err := q.db.Query(ctx, getThreadPosts, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThreadPostsRow
	for rows.Next() {
		var i GetThreadPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.ParentPostID,
			&i.UserID,
			&i.CharacterID,
			&i.Content,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadMessageCount = `-- name: GetUnreadMessageCount :one
SELECT COUNT(*)
FROM private_messages pm
JOIN conversation_participants cp ON pm.conversation_id = cp.conversation_id
WHERE cp.user_id = $1 AND cp.conversation_id = $2
  AND pm.created_at > cp.last_read_at
  AND pm.sender_user_id != $1
`

type GetUnreadMessageCountParams struct {
	UserID         int32
	ConversationID int32
}

func (q *Queries) GetUnreadMessageCount(ctx context.Context, arg GetUnreadMessageCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadMessageCount, arg.UserID, arg.ConversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserConversations = `-- name: GetUserConversations :many
SELECT c.id, c.game_id, c.conversation_type, c.title, c.created_by_user_id, c.created_at, c.updated_at,
       (SELECT COUNT(*) FROM conversation_participants WHERE conversation_id = c.id) as participant_count,
       (SELECT content FROM private_messages WHERE conversation_id = c.id ORDER BY created_at DESC LIMIT 1) as last_message,
       (SELECT created_at FROM private_messages WHERE conversation_id = c.id ORDER BY created_at DESC LIMIT 1) as last_message_at
FROM conversations c
JOIN conversation_participants cp ON c.id = cp.conversation_id
WHERE cp.user_id = $1 AND c.game_id = $2
ORDER BY c.updated_at DESC
`

type GetUserConversationsParams struct {
	UserID int32
	GameID int32
}

type GetUserConversationsRow struct {
	ID               int32
	GameID           int32
	ConversationType string
	Title            pgtype.Text
	CreatedByUserID  int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ParticipantCount int64
	LastMessage      string
	LastMessageAt    pgtype.Timestamptz
}

func (q *Queries) GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, getUserConversations, arg.UserID, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserConversationsRow
	for rows.Next() {
		var i GetUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.ConversationType,
			&i.Title,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParticipantCount,
			&i.LastMessage,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserInConversation = `-- name: IsUserInConversation :one
SELECT EXISTS(
    SELECT 1 FROM conversation_participants
    WHERE conversation_id = $1 AND user_id = $2
)
`

type IsUserInConversationParams struct {
	ConversationID int32
	UserID         int32
}

func (q *Queries) IsUserInConversation(ctx context.Context, arg IsUserInConversationParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInConversation, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeConversationParticipant = `-- name: RemoveConversationParticipant :exec
DELETE FROM conversation_participants
WHERE conversation_id = $1 AND user_id = $2 AND
      (character_id = $3 OR ($3 IS NULL AND character_id IS NULL))
`

type RemoveConversationParticipantParams struct {
	ConversationID int32
	UserID         int32
	CharacterID    pgtype.Int4
}

func (q *Queries) RemoveConversationParticipant(ctx context.Context, arg RemoveConversationParticipantParams) error {
	_, err := q.db.Exec(ctx, removeConversationParticipant, arg.ConversationID, arg.UserID, arg.CharacterID)
	return err
}

const sendPrivateMessage = `-- name: SendPrivateMessage :one
INSERT INTO private_messages (conversation_id, sender_user_id, sender_character_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_user_id, sender_character_id, content, created_at, updated_at
`

type SendPrivateMessageParams struct {
	ConversationID    int32
	SenderUserID      int32
	SenderCharacterID pgtype.Int4
	Content           string
}

func (q *Queries) SendPrivateMessage(ctx context.Context, arg SendPrivateMessageParams) (PrivateMessage, error) {
	row := q.db.QueryRow(ctx, sendPrivateMessage,
		arg.ConversationID,
		arg.SenderUserID,
		arg.SenderCharacterID,
		arg.Content,
	)
	var i PrivateMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.SenderCharacterID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const toggleThreadPin = `-- name: ToggleThreadPin :one
UPDATE threads
SET is_pinned = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, game_id, phase_id, created_by_user_id, title, content, is_pinned, created_at, updated_at
`

type ToggleThreadPinParams struct {
	ID       int32
	IsPinned pgtype.Bool
}

func (q *Queries) ToggleThreadPin(ctx context.Context, arg ToggleThreadPinParams) (Thread, error) {
	row := q.db.QueryRow(ctx, toggleThreadPin, arg.ID, arg.IsPinned)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConversationActivity = `-- name: UpdateConversationActivity :exec
UPDATE conversations
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateConversationActivity(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateConversationActivity, id)
	return err
}

const updateLastReadTime = `-- name: UpdateLastReadTime :exec
UPDATE conversation_participants
SET last_read_at = NOW()
WHERE conversation_id = $1 AND user_id = $2
`

type UpdateLastReadTimeParams struct {
	ConversationID int32
	UserID         int32
}

func (q *Queries) UpdateLastReadTime(ctx context.Context, arg UpdateLastReadTimeParams) error {
	_, err := q.db.Exec(ctx, updateLastReadTime, arg.ConversationID, arg.UserID)
	return err
}

const updateThread = `-- name: UpdateThread :one
UPDATE threads
SET title = $2, content = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, game_id, phase_id, created_by_user_id, title, content, is_pinned, created_at, updated_at
`

type UpdateThreadParams struct {
	ID      int32
	Title   string
	Content string
}

func (q *Queries) UpdateThread(ctx context.Context, arg UpdateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, updateThread, arg.ID, arg.Title, arg.Content)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Content,
		&i.IsPinned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateThreadActivity = `-- name: UpdateThreadActivity :exec
UPDATE threads
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateThreadActivity(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateThreadActivity, id)
	return err
}

const updateThreadPost = `-- name: UpdateThreadPost :one
UPDATE thread_posts
SET content = $2, is_edited = true, updated_at = NOW()
WHERE id = $1
RETURNING id, thread_id, parent_post_id, user_id, character_id, content, is_edited, created_at, updated_at
`

type UpdateThreadPostParams struct {
	ID      int32
	Content string
}

func (q *Queries) UpdateThreadPost(ctx context.Context, arg UpdateThreadPostParams) (ThreadPost, error) {
	row := q.db.QueryRow(ctx, updateThreadPost, arg.ID, arg.Content)
	var i ThreadPost
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ParentPostID,
		&i.UserID,
		&i.CharacterID,
		&i.Content,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
