// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGameParticipant = `-- name: AddGameParticipant :one
INSERT INTO game_participants (game_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, game_id, user_id, role, status, joined_at
`

type AddGameParticipantParams struct {
	GameID int32
	UserID int32
	Role   string
}

func (q *Queries) AddGameParticipant(ctx context.Context, arg AddGameParticipantParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, addGameParticipant, arg.GameID, arg.UserID, arg.Role)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (
    title, description, gm_user_id, genre, start_date, end_date,
    recruitment_deadline, max_players, is_public
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, created_at, updated_at
`

type CreateGameParams struct {
	Title               string
	Description         string
	GmUserID            int32
	Genre               pgtype.Text
	StartDate           pgtype.Timestamptz
	EndDate             pgtype.Timestamptz
	RecruitmentDeadline pgtype.Timestamptz
	MaxPlayers          pgtype.Int4
	IsPublic            pgtype.Bool
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.Title,
		arg.Description,
		arg.GmUserID,
		arg.Genre,
		arg.StartDate,
		arg.EndDate,
		arg.RecruitmentDeadline,
		arg.MaxPlayers,
		arg.IsPublic,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getAllGames = `-- name: GetAllGames :many
SELECT games.id, games.title, games.description, games.gm_user_id, games.state, games.genre, games.start_date, games.end_date, games.recruitment_deadline, games.max_players, games.is_public, games.created_at, games.updated_at, COALESCE(users.username, 'Unknown') as gm_username
FROM games
LEFT JOIN users ON games.gm_user_id = users.id
WHERE games.is_public = true
ORDER BY games.id DESC
`

type GetAllGamesRow struct {
	ID                  int32
	Title               string
	Description         string
	GmUserID            int32
	State               string
	Genre               pgtype.Text
	StartDate           pgtype.Timestamptz
	EndDate             pgtype.Timestamptz
	RecruitmentDeadline pgtype.Timestamptz
	MaxPlayers          pgtype.Int4
	IsPublic            pgtype.Bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	GmUsername          string
}

func (q *Queries) GetAllGames(ctx context.Context) ([]GetAllGamesRow, error) {
	rows, err := q.db.Query(ctx, getAllGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllGamesRow
	for rows.Next() {
		var i GetAllGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GmUserID,
			&i.State,
			&i.Genre,
			&i.StartDate,
			&i.EndDate,
			&i.RecruitmentDeadline,
			&i.MaxPlayers,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GmUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGame = `-- name: GetGame :one
SELECT id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, created_at, updated_at FROM games WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameParticipantCount = `-- name: GetGameParticipantCount :one
SELECT COUNT(*) FROM game_participants
WHERE game_id = $1 AND role = 'player' AND status = 'active'
`

func (q *Queries) GetGameParticipantCount(ctx context.Context, gameID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getGameParticipantCount, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGameParticipants = `-- name: GetGameParticipants :many
SELECT gp.id, gp.game_id, gp.user_id, gp.role, gp.status, gp.joined_at, u.username, u.email
FROM game_participants gp
JOIN users u ON gp.user_id = u.id
WHERE gp.game_id = $1 AND gp.status = 'active'
ORDER BY gp.joined_at
`

type GetGameParticipantsRow struct {
	ID       int32
	GameID   int32
	UserID   int32
	Role     string
	Status   string
	JoinedAt pgtype.Timestamptz
	Username string
	Email    string
}

func (q *Queries) GetGameParticipants(ctx context.Context, gameID int32) ([]GetGameParticipantsRow, error) {
	rows, err := q.db.Query(ctx, getGameParticipants, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameParticipantsRow
	for rows.Next() {
		var i GetGameParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesByGM = `-- name: GetGamesByGM :many
SELECT id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, created_at, updated_at FROM games WHERE gm_user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetGamesByGM(ctx context.Context, gmUserID int32) ([]Game, error) {
	rows, err := q.db.Query(ctx, getGamesByGM, gmUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GmUserID,
			&i.State,
			&i.Genre,
			&i.StartDate,
			&i.EndDate,
			&i.RecruitmentDeadline,
			&i.MaxPlayers,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamesByUser = `-- name: GetGamesByUser :many
SELECT g.id, g.title, g.description, g.gm_user_id, g.state, g.genre, g.start_date, g.end_date, g.recruitment_deadline, g.max_players, g.is_public, g.created_at, g.updated_at, gp.role as user_role, u.username as gm_username
FROM games g
JOIN game_participants gp ON g.id = gp.game_id
JOIN users u ON g.gm_user_id = u.id
WHERE gp.user_id = $1 AND gp.status = 'active'
ORDER BY g.updated_at DESC
`

type GetGamesByUserRow struct {
	ID                  int32
	Title               string
	Description         string
	GmUserID            int32
	State               string
	Genre               pgtype.Text
	StartDate           pgtype.Timestamptz
	EndDate             pgtype.Timestamptz
	RecruitmentDeadline pgtype.Timestamptz
	MaxPlayers          pgtype.Int4
	IsPublic            pgtype.Bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	UserRole            string
	GmUsername          string
}

func (q *Queries) GetGamesByUser(ctx context.Context, userID int32) ([]GetGamesByUserRow, error) {
	rows, err := q.db.Query(ctx, getGamesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamesByUserRow
	for rows.Next() {
		var i GetGamesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GmUserID,
			&i.State,
			&i.Genre,
			&i.StartDate,
			&i.EndDate,
			&i.RecruitmentDeadline,
			&i.MaxPlayers,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserRole,
			&i.GmUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipantRole = `-- name: GetParticipantRole :one
SELECT role FROM game_participants
WHERE game_id = $1 AND user_id = $2 AND status = 'active'
`

type GetParticipantRoleParams struct {
	GameID int32
	UserID int32
}

func (q *Queries) GetParticipantRole(ctx context.Context, arg GetParticipantRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getParticipantRole, arg.GameID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const isUserInGame = `-- name: IsUserInGame :one
SELECT EXISTS(
    SELECT 1 FROM game_participants
    WHERE game_id = $1 AND user_id = $2 AND status = 'active'
)
`

type IsUserInGameParams struct {
	GameID int32
	UserID int32
}

func (q *Queries) IsUserInGame(ctx context.Context, arg IsUserInGameParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInGame, arg.GameID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeGameParticipant = `-- name: RemoveGameParticipant :exec
DELETE FROM game_participants
WHERE game_id = $1 AND user_id = $2
`

type RemoveGameParticipantParams struct {
	GameID int32
	UserID int32
}

func (q *Queries) RemoveGameParticipant(ctx context.Context, arg RemoveGameParticipantParams) error {
	_, err := q.db.Exec(ctx, removeGameParticipant, arg.GameID, arg.UserID)
	return err
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET title = $2, description = $3, genre = $4, start_date = $5,
    end_date = $6, recruitment_deadline = $7, max_players = $8,
    is_public = $9, updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, created_at, updated_at
`

type UpdateGameParams struct {
	ID                  int32
	Title               string
	Description         string
	Genre               pgtype.Text
	StartDate           pgtype.Timestamptz
	EndDate             pgtype.Timestamptz
	RecruitmentDeadline pgtype.Timestamptz
	MaxPlayers          pgtype.Int4
	IsPublic            pgtype.Bool
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGame,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Genre,
		arg.StartDate,
		arg.EndDate,
		arg.RecruitmentDeadline,
		arg.MaxPlayers,
		arg.IsPublic,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGameState = `-- name: UpdateGameState :one
UPDATE games
SET state = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, gm_user_id, state, genre, start_date, end_date, recruitment_deadline, max_players, is_public, created_at, updated_at
`

type UpdateGameStateParams struct {
	ID    int32
	State string
}

func (q *Queries) UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error) {
	row := q.db.QueryRow(ctx, updateGameState, arg.ID, arg.State)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GmUserID,
		&i.State,
		&i.Genre,
		&i.StartDate,
		&i.EndDate,
		&i.RecruitmentDeadline,
		&i.MaxPlayers,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateParticipantStatus = `-- name: UpdateParticipantStatus :one
UPDATE game_participants
SET status = $3
WHERE game_id = $1 AND user_id = $2
RETURNING id, game_id, user_id, role, status, joined_at
`

type UpdateParticipantStatusParams struct {
	GameID int32
	UserID int32
	Status string
}

func (q *Queries) UpdateParticipantStatus(ctx context.Context, arg UpdateParticipantStatusParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantStatus, arg.GameID, arg.UserID, arg.Status)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}
