// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: game_applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkApproveApplications = `-- name: BulkApproveApplications :exec
UPDATE game_applications
SET
    status = 'approved',
    reviewed_at = NOW(),
    reviewed_by_user_id = $2
WHERE game_id = $1 AND status = 'pending'
`

type BulkApproveApplicationsParams struct {
	GameID           int32
	ReviewedByUserID pgtype.Int4
}

func (q *Queries) BulkApproveApplications(ctx context.Context, arg BulkApproveApplicationsParams) error {
	_, err := q.db.Exec(ctx, bulkApproveApplications, arg.GameID, arg.ReviewedByUserID)
	return err
}

const canUserApplyToGame = `-- name: CanUserApplyToGame :one
SELECT CASE
    WHEN EXISTS(SELECT 1 FROM game_participants gp WHERE gp.game_id = $1 AND gp.user_id = $2) THEN 'already_participant'
    WHEN EXISTS(SELECT 1 FROM game_applications ga WHERE ga.game_id = $1 AND ga.user_id = $2 AND ga.status = 'pending') THEN 'application_pending'
    WHEN EXISTS(SELECT 1 FROM game_applications ga2 WHERE ga2.game_id = $1 AND ga2.user_id = $2 AND ga2.status = 'rejected') THEN 'application_rejected'
    WHEN EXISTS(SELECT 1 FROM games g WHERE g.id = $1 AND g.state != 'recruitment') THEN 'not_recruiting'
    ELSE 'can_apply'
END AS status
`

type CanUserApplyToGameParams struct {
	GameID int32
	UserID int32
}

func (q *Queries) CanUserApplyToGame(ctx context.Context, arg CanUserApplyToGameParams) (string, error) {
	row := q.db.QueryRow(ctx, canUserApplyToGame, arg.GameID, arg.UserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const countPendingApplicationsForGame = `-- name: CountPendingApplicationsForGame :one
SELECT COUNT(*) FROM game_applications
WHERE game_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingApplicationsForGame(ctx context.Context, gameID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingApplicationsForGame, gameID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGameApplication = `-- name: CreateGameApplication :one
INSERT INTO game_applications (
    game_id, user_id, role, message
) VALUES (
    $1, $2, $3, $4
) RETURNING id, game_id, user_id, role, message, status, reviewed_by_user_id, reviewed_at, applied_at, created_at, updated_at
`

type CreateGameApplicationParams struct {
	GameID  int32
	UserID  int32
	Role    string
	Message pgtype.Text
}

func (q *Queries) CreateGameApplication(ctx context.Context, arg CreateGameApplicationParams) (GameApplication, error) {
	row := q.db.QueryRow(ctx, createGameApplication,
		arg.GameID,
		arg.UserID,
		arg.Role,
		arg.Message,
	)
	var i GameApplication
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGameApplication = `-- name: DeleteGameApplication :exec
DELETE FROM game_applications WHERE id = $1 AND user_id = $2
`

type DeleteGameApplicationParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteGameApplication(ctx context.Context, arg DeleteGameApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteGameApplication, arg.ID, arg.UserID)
	return err
}

const getApprovedApplicationsForGame = `-- name: GetApprovedApplicationsForGame :many
SELECT
    ga.id, ga.game_id, ga.user_id, ga.role, ga.message, ga.status, ga.reviewed_by_user_id, ga.reviewed_at, ga.applied_at, ga.created_at, ga.updated_at,
    u.username,
    u.email
FROM game_applications ga
JOIN users u ON ga.user_id = u.id
WHERE ga.game_id = $1 AND ga.status = 'approved'
ORDER BY ga.reviewed_at ASC
`

type GetApprovedApplicationsForGameRow struct {
	ID               int32
	GameID           int32
	UserID           int32
	Role             string
	Message          pgtype.Text
	Status           pgtype.Text
	ReviewedByUserID pgtype.Int4
	ReviewedAt       pgtype.Timestamptz
	AppliedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Username         string
	Email            string
}

func (q *Queries) GetApprovedApplicationsForGame(ctx context.Context, gameID int32) ([]GetApprovedApplicationsForGameRow, error) {
	rows, err := q.db.Query(ctx, getApprovedApplicationsForGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApprovedApplicationsForGameRow
	for rows.Next() {
		var i GetApprovedApplicationsForGameRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Message,
			&i.Status,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameApplication = `-- name: GetGameApplication :one
SELECT id, game_id, user_id, role, message, status, reviewed_by_user_id, reviewed_at, applied_at, created_at, updated_at FROM game_applications WHERE id = $1
`

func (q *Queries) GetGameApplication(ctx context.Context, id int32) (GameApplication, error) {
	row := q.db.QueryRow(ctx, getGameApplication, id)
	var i GameApplication
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameApplicationByUserAndGame = `-- name: GetGameApplicationByUserAndGame :one
SELECT id, game_id, user_id, role, message, status, reviewed_by_user_id, reviewed_at, applied_at, created_at, updated_at FROM game_applications
WHERE game_id = $1 AND user_id = $2
`

type GetGameApplicationByUserAndGameParams struct {
	GameID int32
	UserID int32
}

func (q *Queries) GetGameApplicationByUserAndGame(ctx context.Context, arg GetGameApplicationByUserAndGameParams) (GameApplication, error) {
	row := q.db.QueryRow(ctx, getGameApplicationByUserAndGame, arg.GameID, arg.UserID)
	var i GameApplication
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGameApplications = `-- name: GetGameApplications :many
SELECT
    ga.id, ga.game_id, ga.user_id, ga.role, ga.message, ga.status, ga.reviewed_by_user_id, ga.reviewed_at, ga.applied_at, ga.created_at, ga.updated_at,
    u.username,
    u.email
FROM game_applications ga
JOIN users u ON ga.user_id = u.id
WHERE ga.game_id = $1
ORDER BY ga.applied_at ASC
`

type GetGameApplicationsRow struct {
	ID               int32
	GameID           int32
	UserID           int32
	Role             string
	Message          pgtype.Text
	Status           pgtype.Text
	ReviewedByUserID pgtype.Int4
	ReviewedAt       pgtype.Timestamptz
	AppliedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Username         string
	Email            string
}

func (q *Queries) GetGameApplications(ctx context.Context, gameID int32) ([]GetGameApplicationsRow, error) {
	rows, err := q.db.Query(ctx, getGameApplications, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameApplicationsRow
	for rows.Next() {
		var i GetGameApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Message,
			&i.Status,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameApplicationsByStatus = `-- name: GetGameApplicationsByStatus :many
SELECT
    ga.id, ga.game_id, ga.user_id, ga.role, ga.message, ga.status, ga.reviewed_by_user_id, ga.reviewed_at, ga.applied_at, ga.created_at, ga.updated_at,
    u.username,
    u.email
FROM game_applications ga
JOIN users u ON ga.user_id = u.id
WHERE ga.game_id = $1 AND ga.status = $2
ORDER BY ga.applied_at ASC
`

type GetGameApplicationsByStatusParams struct {
	GameID int32
	Status pgtype.Text
}

type GetGameApplicationsByStatusRow struct {
	ID               int32
	GameID           int32
	UserID           int32
	Role             string
	Message          pgtype.Text
	Status           pgtype.Text
	ReviewedByUserID pgtype.Int4
	ReviewedAt       pgtype.Timestamptz
	AppliedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Username         string
	Email            string
}

func (q *Queries) GetGameApplicationsByStatus(ctx context.Context, arg GetGameApplicationsByStatusParams) ([]GetGameApplicationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getGameApplicationsByStatus, arg.GameID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameApplicationsByStatusRow
	for rows.Next() {
		var i GetGameApplicationsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Message,
			&i.Status,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGameApplications = `-- name: GetUserGameApplications :many
SELECT
    ga.id, ga.game_id, ga.user_id, ga.role, ga.message, ga.status, ga.reviewed_by_user_id, ga.reviewed_at, ga.applied_at, ga.created_at, ga.updated_at,
    g.title AS game_title,
    g.state AS game_state
FROM game_applications ga
JOIN games g ON ga.game_id = g.id
WHERE ga.user_id = $1
ORDER BY ga.applied_at DESC
`

type GetUserGameApplicationsRow struct {
	ID               int32
	GameID           int32
	UserID           int32
	Role             string
	Message          pgtype.Text
	Status           pgtype.Text
	ReviewedByUserID pgtype.Int4
	ReviewedAt       pgtype.Timestamptz
	AppliedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	GameTitle        string
	GameState        pgtype.Text
}

func (q *Queries) GetUserGameApplications(ctx context.Context, userID int32) ([]GetUserGameApplicationsRow, error) {
	rows, err := q.db.Query(ctx, getUserGameApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserGameApplicationsRow
	for rows.Next() {
		var i GetUserGameApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.Role,
			&i.Message,
			&i.Status,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GameTitle,
			&i.GameState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserAppliedToGame = `-- name: HasUserAppliedToGame :one
SELECT EXISTS(
    SELECT 1 FROM game_applications
    WHERE game_id = $1 AND user_id = $2
)
`

type HasUserAppliedToGameParams struct {
	GameID int32
	UserID int32
}

func (q *Queries) HasUserAppliedToGame(ctx context.Context, arg HasUserAppliedToGameParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserAppliedToGame, arg.GameID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateGameApplicationStatus = `-- name: UpdateGameApplicationStatus :one
UPDATE game_applications
SET
    status = $2,
    reviewed_at = NOW(),
    reviewed_by_user_id = $3
WHERE id = $1
RETURNING id, game_id, user_id, role, message, status, reviewed_by_user_id, reviewed_at, applied_at, created_at, updated_at
`

type UpdateGameApplicationStatusParams struct {
	ID               int32
	Status           pgtype.Text
	ReviewedByUserID pgtype.Int4
}

func (q *Queries) UpdateGameApplicationStatus(ctx context.Context, arg UpdateGameApplicationStatusParams) (GameApplication, error) {
	row := q.db.QueryRow(ctx, updateGameApplicationStatus, arg.ID, arg.Status, arg.ReviewedByUserID)
	var i GameApplication
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.Role,
		&i.Message,
		&i.Status,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawGameApplication = `-- name: WithdrawGameApplication :exec
UPDATE game_applications
SET
    status = 'withdrawn',
    reviewed_at = NOW()
WHERE id = $1 AND user_id = $2
`

type WithdrawGameApplicationParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) WithdrawGameApplication(ctx context.Context, arg WithdrawGameApplicationParams) error {
	_, err := q.db.Exec(ctx, withdrawGameApplication, arg.ID, arg.UserID)
	return err
}
