// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :one

INSERT INTO message_reactions (message_id, user_id, reaction_type)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, user_id, reaction_type) DO NOTHING
RETURNING id, message_id, user_id, reaction_type, created_at
`

type AddReactionParams struct {
	MessageID    int32  `json:"message_id"`
	UserID       int32  `json:"user_id"`
	ReactionType string `json:"reaction_type"`
}

// ============================================================================
// REACTIONS (Optional - for future use)
// ============================================================================
func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) (MessageReaction, error) {
	row := q.db.QueryRow(ctx, addReaction, arg.MessageID, arg.UserID, arg.ReactionType)
	var i MessageReaction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.ReactionType,
		&i.CreatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO messages (
    game_id,
    phase_id,
    author_id,
    character_id,
    content,
    message_type,
    parent_id,
    visibility
) VALUES (
    $1, $2, $3, $4, $5, 'comment', $6, $7
)
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, is_edited, is_deleted, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	GameID      int32             `json:"game_id"`
	PhaseID     pgtype.Int4       `json:"phase_id"`
	AuthorID    int32             `json:"author_id"`
	CharacterID int32             `json:"character_id"`
	Content     string            `json:"content"`
	ParentID    pgtype.Int4       `json:"parent_id"`
	Visibility  MessageVisibility `json:"visibility"`
}

// ============================================================================
// COMMENT MANAGEMENT (Threaded replies)
// ============================================================================
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Message, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.GameID,
		arg.PhaseID,
		arg.AuthorID,
		arg.CharacterID,
		arg.Content,
		arg.ParentID,
		arg.Visibility,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one


INSERT INTO messages (
    game_id,
    phase_id,
    author_id,
    character_id,
    content,
    message_type,
    visibility
) VALUES (
    $1, $2, $3, $4, $5, 'post', $6
)
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, is_edited, is_deleted, created_at, updated_at, deleted_at
`

type CreatePostParams struct {
	GameID      int32             `json:"game_id"`
	PhaseID     pgtype.Int4       `json:"phase_id"`
	AuthorID    int32             `json:"author_id"`
	CharacterID int32             `json:"character_id"`
	Content     string            `json:"content"`
	Visibility  MessageVisibility `json:"visibility"`
}

// Messages Queries (Common Room posts and future private messages)
// ============================================================================
// POST MANAGEMENT (Top-level messages)
// ============================================================================
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Message, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.GameID,
		arg.PhaseID,
		arg.AuthorID,
		arg.CharacterID,
		arg.Content,
		arg.Visibility,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
UPDATE messages
SET is_deleted = true
WHERE id = $1
  AND message_type = 'comment'
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, is_edited, is_deleted, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) (Message, error) {
	row := q.db.QueryRow(ctx, deleteComment, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :one
UPDATE messages
SET is_deleted = true
WHERE id = $1
  AND message_type = 'post'
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, is_edited, is_deleted, created_at, updated_at, deleted_at
`

func (q *Queries) DeletePost(ctx context.Context, id int32) (Message, error) {
	row := q.db.QueryRow(ctx, deletePost, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllDescendantComments = `-- name: GetAllDescendantComments :many
WITH RECURSIVE comment_tree AS (
  SELECT messages.id as comment_id
  FROM messages
  WHERE messages.parent_id = $1 AND messages.is_deleted = false

  UNION ALL

  SELECT m.id as comment_id
  FROM messages m
  INNER JOIN comment_tree ct ON m.parent_id = ct.comment_id
  WHERE m.is_deleted = false
)
SELECT comment_id as id FROM comment_tree
`

// Get all descendant comments recursively for counting
func (q *Queries) GetAllDescendantComments(ctx context.Context, parentID pgtype.Int4) ([]int32, error) {
	rows, err := q.db.Query(ctx, getAllDescendantComments, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComment = `-- name: GetComment :one
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.is_edited, m.is_deleted, m.created_at, m.updated_at, m.deleted_at,
       u.username as author_username,
       c.name as character_name,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id AND is_deleted = false) as reply_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.id = $1
`

type GetCommentRow struct {
	ID             int32             `json:"id"`
	GameID         int32             `json:"game_id"`
	PhaseID        pgtype.Int4       `json:"phase_id"`
	AuthorID       int32             `json:"author_id"`
	CharacterID    int32             `json:"character_id"`
	Content        string            `json:"content"`
	MessageType    MessageType       `json:"message_type"`
	ParentID       pgtype.Int4       `json:"parent_id"`
	ThreadDepth    int32             `json:"thread_depth"`
	Visibility     MessageVisibility `json:"visibility"`
	IsEdited       bool              `json:"is_edited"`
	IsDeleted      bool              `json:"is_deleted"`
	CreatedAt      pgtype.Timestamp  `json:"created_at"`
	UpdatedAt      pgtype.Timestamp  `json:"updated_at"`
	DeletedAt      pgtype.Timestamp  `json:"deleted_at"`
	AuthorUsername string            `json:"author_username"`
	CharacterName  pgtype.Text       `json:"character_name"`
	ReplyCount     int64             `json:"reply_count"`
}

func (q *Queries) GetComment(ctx context.Context, id int32) (GetCommentRow, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AuthorUsername,
		&i.CharacterName,
		&i.ReplyCount,
	)
	return i, err
}

const getGamePostCount = `-- name: GetGamePostCount :one

SELECT COUNT(*)
FROM messages
WHERE game_id = $1
  AND message_type = 'post'
  AND is_deleted = false
  AND (CASE WHEN $2 = 0 THEN TRUE ELSE phase_id = $2 END)
`

type GetGamePostCountParams struct {
	GameID  int32       `json:"game_id"`
	Column2 interface{} `json:"column_2"`
}

// ============================================================================
// STATISTICS & COUNTS
// ============================================================================
func (q *Queries) GetGamePostCount(ctx context.Context, arg GetGamePostCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getGamePostCount, arg.GameID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGamePosts = `-- name: GetGamePosts :many
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.is_edited, m.is_deleted, m.created_at, m.updated_at, m.deleted_at,
       u.username as author_username,
       c.name as character_name,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id AND is_deleted = false) as comment_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.game_id = $1
  AND m.message_type = 'post'
  AND m.is_deleted = false
  AND (CASE WHEN $2 = 0 THEN TRUE ELSE m.phase_id = $2 END)
ORDER BY m.created_at DESC
LIMIT $3 OFFSET $4
`

type GetGamePostsParams struct {
	GameID  int32       `json:"game_id"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type GetGamePostsRow struct {
	ID             int32             `json:"id"`
	GameID         int32             `json:"game_id"`
	PhaseID        pgtype.Int4       `json:"phase_id"`
	AuthorID       int32             `json:"author_id"`
	CharacterID    int32             `json:"character_id"`
	Content        string            `json:"content"`
	MessageType    MessageType       `json:"message_type"`
	ParentID       pgtype.Int4       `json:"parent_id"`
	ThreadDepth    int32             `json:"thread_depth"`
	Visibility     MessageVisibility `json:"visibility"`
	IsEdited       bool              `json:"is_edited"`
	IsDeleted      bool              `json:"is_deleted"`
	CreatedAt      pgtype.Timestamp  `json:"created_at"`
	UpdatedAt      pgtype.Timestamp  `json:"updated_at"`
	DeletedAt      pgtype.Timestamp  `json:"deleted_at"`
	AuthorUsername string            `json:"author_username"`
	CharacterName  pgtype.Text       `json:"character_name"`
	CommentCount   int64             `json:"comment_count"`
}

func (q *Queries) GetGamePosts(ctx context.Context, arg GetGamePostsParams) ([]GetGamePostsRow, error) {
	rows, err := q.db.Query(ctx, getGamePosts,
		arg.GameID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGamePostsRow
	for rows.Next() {
		var i GetGamePostsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.ParentID,
			&i.ThreadDepth,
			&i.Visibility,
			&i.IsEdited,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageReactions = `-- name: GetMessageReactions :many
SELECT mr.id, mr.message_id, mr.user_id, mr.reaction_type, mr.created_at, u.username
FROM message_reactions mr
JOIN users u ON mr.user_id = u.id
WHERE mr.message_id = $1
ORDER BY mr.created_at
`

type GetMessageReactionsRow struct {
	ID           int32            `json:"id"`
	MessageID    int32            `json:"message_id"`
	UserID       int32            `json:"user_id"`
	ReactionType string           `json:"reaction_type"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	Username     string           `json:"username"`
}

func (q *Queries) GetMessageReactions(ctx context.Context, messageID int32) ([]GetMessageReactionsRow, error) {
	rows, err := q.db.Query(ctx, getMessageReactions, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageReactionsRow
	for rows.Next() {
		var i GetMessageReactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.ReactionType,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhasePosts = `-- name: GetPhasePosts :many
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.is_edited, m.is_deleted, m.created_at, m.updated_at, m.deleted_at,
       u.username as author_username,
       c.name as character_name,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id AND is_deleted = false) as comment_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.phase_id = $1
  AND m.message_type = 'post'
  AND m.is_deleted = false
ORDER BY m.created_at DESC
`

type GetPhasePostsRow struct {
	ID             int32             `json:"id"`
	GameID         int32             `json:"game_id"`
	PhaseID        pgtype.Int4       `json:"phase_id"`
	AuthorID       int32             `json:"author_id"`
	CharacterID    int32             `json:"character_id"`
	Content        string            `json:"content"`
	MessageType    MessageType       `json:"message_type"`
	ParentID       pgtype.Int4       `json:"parent_id"`
	ThreadDepth    int32             `json:"thread_depth"`
	Visibility     MessageVisibility `json:"visibility"`
	IsEdited       bool              `json:"is_edited"`
	IsDeleted      bool              `json:"is_deleted"`
	CreatedAt      pgtype.Timestamp  `json:"created_at"`
	UpdatedAt      pgtype.Timestamp  `json:"updated_at"`
	DeletedAt      pgtype.Timestamp  `json:"deleted_at"`
	AuthorUsername string            `json:"author_username"`
	CharacterName  pgtype.Text       `json:"character_name"`
	CommentCount   int64             `json:"comment_count"`
}

func (q *Queries) GetPhasePosts(ctx context.Context, phaseID pgtype.Int4) ([]GetPhasePostsRow, error) {
	rows, err := q.db.Query(ctx, getPhasePosts, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhasePostsRow
	for rows.Next() {
		var i GetPhasePostsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.ParentID,
			&i.ThreadDepth,
			&i.Visibility,
			&i.IsEdited,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPost = `-- name: GetPost :one
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.is_edited, m.is_deleted, m.created_at, m.updated_at, m.deleted_at,
       u.username as author_username,
       c.name as character_name,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id AND is_deleted = false) as comment_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.id = $1
`

type GetPostRow struct {
	ID             int32             `json:"id"`
	GameID         int32             `json:"game_id"`
	PhaseID        pgtype.Int4       `json:"phase_id"`
	AuthorID       int32             `json:"author_id"`
	CharacterID    int32             `json:"character_id"`
	Content        string            `json:"content"`
	MessageType    MessageType       `json:"message_type"`
	ParentID       pgtype.Int4       `json:"parent_id"`
	ThreadDepth    int32             `json:"thread_depth"`
	Visibility     MessageVisibility `json:"visibility"`
	IsEdited       bool              `json:"is_edited"`
	IsDeleted      bool              `json:"is_deleted"`
	CreatedAt      pgtype.Timestamp  `json:"created_at"`
	UpdatedAt      pgtype.Timestamp  `json:"updated_at"`
	DeletedAt      pgtype.Timestamp  `json:"deleted_at"`
	AuthorUsername string            `json:"author_username"`
	CharacterName  pgtype.Text       `json:"character_name"`
	CommentCount   int64             `json:"comment_count"`
}

func (q *Queries) GetPost(ctx context.Context, id int32) (GetPostRow, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AuthorUsername,
		&i.CharacterName,
		&i.CommentCount,
	)
	return i, err
}

const getPostCommentCount = `-- name: GetPostCommentCount :one
SELECT COUNT(*)
FROM messages
WHERE parent_id = $1
  AND is_deleted = false
`

func (q *Queries) GetPostCommentCount(ctx context.Context, parentID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, getPostCommentCount, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPostComments = `-- name: GetPostComments :many
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.is_edited, m.is_deleted, m.created_at, m.updated_at, m.deleted_at,
       u.username as author_username,
       c.name as character_name,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id AND is_deleted = false) as reply_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.parent_id = $1
  AND m.message_type = 'comment'
  AND m.is_deleted = false
ORDER BY m.created_at ASC
`

type GetPostCommentsRow struct {
	ID             int32             `json:"id"`
	GameID         int32             `json:"game_id"`
	PhaseID        pgtype.Int4       `json:"phase_id"`
	AuthorID       int32             `json:"author_id"`
	CharacterID    int32             `json:"character_id"`
	Content        string            `json:"content"`
	MessageType    MessageType       `json:"message_type"`
	ParentID       pgtype.Int4       `json:"parent_id"`
	ThreadDepth    int32             `json:"thread_depth"`
	Visibility     MessageVisibility `json:"visibility"`
	IsEdited       bool              `json:"is_edited"`
	IsDeleted      bool              `json:"is_deleted"`
	CreatedAt      pgtype.Timestamp  `json:"created_at"`
	UpdatedAt      pgtype.Timestamp  `json:"updated_at"`
	DeletedAt      pgtype.Timestamp  `json:"deleted_at"`
	AuthorUsername string            `json:"author_username"`
	CharacterName  pgtype.Text       `json:"character_name"`
	ReplyCount     int64             `json:"reply_count"`
}

// Get direct comments for a specific post
// For threaded display, call this recursively on the frontend
func (q *Queries) GetPostComments(ctx context.Context, parentID pgtype.Int4) ([]GetPostCommentsRow, error) {
	rows, err := q.db.Query(ctx, getPostComments, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostCommentsRow
	for rows.Next() {
		var i GetPostCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.ParentID,
			&i.ThreadDepth,
			&i.Visibility,
			&i.IsEdited,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReactionCounts = `-- name: GetReactionCounts :many
SELECT reaction_type, COUNT(*) as count
FROM message_reactions
WHERE message_id = $1
GROUP BY reaction_type
`

type GetReactionCountsRow struct {
	ReactionType string `json:"reaction_type"`
	Count        int64  `json:"count"`
}

func (q *Queries) GetReactionCounts(ctx context.Context, messageID int32) ([]GetReactionCountsRow, error) {
	rows, err := q.db.Query(ctx, getReactionCounts, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReactionCountsRow
	for rows.Next() {
		var i GetReactionCountsRow
		if err := rows.Scan(&i.ReactionType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPostsInGame = `-- name: GetUserPostsInGame :many
SELECT m.id, m.game_id, m.phase_id, m.author_id, m.character_id, m.content, m.message_type, m.parent_id, m.thread_depth, m.visibility, m.is_edited, m.is_deleted, m.created_at, m.updated_at, m.deleted_at,
       u.username as author_username,
       c.name as character_name,
       (SELECT COUNT(*) FROM messages WHERE parent_id = m.id AND is_deleted = false) as comment_count
FROM messages m
JOIN users u ON m.author_id = u.id
LEFT JOIN characters c ON m.character_id = c.id
WHERE m.game_id = $1
  AND m.author_id = $2
  AND m.message_type = 'post'
  AND m.is_deleted = false
ORDER BY m.created_at DESC
`

type GetUserPostsInGameParams struct {
	GameID   int32 `json:"game_id"`
	AuthorID int32 `json:"author_id"`
}

type GetUserPostsInGameRow struct {
	ID             int32             `json:"id"`
	GameID         int32             `json:"game_id"`
	PhaseID        pgtype.Int4       `json:"phase_id"`
	AuthorID       int32             `json:"author_id"`
	CharacterID    int32             `json:"character_id"`
	Content        string            `json:"content"`
	MessageType    MessageType       `json:"message_type"`
	ParentID       pgtype.Int4       `json:"parent_id"`
	ThreadDepth    int32             `json:"thread_depth"`
	Visibility     MessageVisibility `json:"visibility"`
	IsEdited       bool              `json:"is_edited"`
	IsDeleted      bool              `json:"is_deleted"`
	CreatedAt      pgtype.Timestamp  `json:"created_at"`
	UpdatedAt      pgtype.Timestamp  `json:"updated_at"`
	DeletedAt      pgtype.Timestamp  `json:"deleted_at"`
	AuthorUsername string            `json:"author_username"`
	CharacterName  pgtype.Text       `json:"character_name"`
	CommentCount   int64             `json:"comment_count"`
}

func (q *Queries) GetUserPostsInGame(ctx context.Context, arg GetUserPostsInGameParams) ([]GetUserPostsInGameRow, error) {
	rows, err := q.db.Query(ctx, getUserPostsInGame, arg.GameID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPostsInGameRow
	for rows.Next() {
		var i GetUserPostsInGameRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseID,
			&i.AuthorID,
			&i.CharacterID,
			&i.Content,
			&i.MessageType,
			&i.ParentID,
			&i.ThreadDepth,
			&i.Visibility,
			&i.IsEdited,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AuthorUsername,
			&i.CharacterName,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM message_reactions
WHERE message_id = $1 AND user_id = $2 AND reaction_type = $3
`

type RemoveReactionParams struct {
	MessageID    int32  `json:"message_id"`
	UserID       int32  `json:"user_id"`
	ReactionType string `json:"reaction_type"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.ReactionType)
	return err
}

const updateComment = `-- name: UpdateComment :one

UPDATE messages
SET content = $2,
    is_edited = true
WHERE id = $1
  AND is_deleted = false
  AND message_type = 'comment'
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, is_edited, is_deleted, created_at, updated_at, deleted_at
`

type UpdateCommentParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

// NOTE: GetCommentThread with recursive CTE is not supported by sqlc
// Use GetPostComments recursively on the frontend to build the tree
// This is actually more efficient for large thread trees anyway
func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE messages
SET content = $2,
    is_edited = true
WHERE id = $1
  AND is_deleted = false
  AND message_type = 'post'
RETURNING id, game_id, phase_id, author_id, character_id, content, message_type, parent_id, thread_depth, visibility, is_edited, is_deleted, created_at, updated_at, deleted_at
`

type UpdatePostParams struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Message, error) {
	row := q.db.QueryRow(ctx, updatePost, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseID,
		&i.AuthorID,
		&i.CharacterID,
		&i.Content,
		&i.MessageType,
		&i.ParentID,
		&i.ThreadDepth,
		&i.Visibility,
		&i.IsEdited,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
