// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActionResult struct {
	ID          int32
	GameID      int32
	UserID      int32
	PhaseID     int32
	GmUserID    int32
	Content     string
	IsPublished pgtype.Bool
	SentAt      pgtype.Timestamptz
}

type ActionSubmission struct {
	ID          int32
	GameID      int32
	UserID      int32
	PhaseID     int32
	CharacterID pgtype.Int4
	Content     string
	IsDraft     pgtype.Bool
	SubmittedAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Character struct {
	ID            int32
	GameID        int32
	UserID        pgtype.Int4
	Name          string
	CharacterType string
	Status        pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type CharacterDatum struct {
	ID          int32
	CharacterID int32
	ModuleType  string
	FieldName   string
	FieldValue  pgtype.Text
	FieldType   pgtype.Text
	IsPublic    pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Conversation struct {
	ID               int32
	GameID           int32
	Title            pgtype.Text
	ConversationType pgtype.Text
	CreatedByUserID  int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ConversationParticipant struct {
	ID             int32
	ConversationID int32
	UserID         pgtype.Int4
	CharacterID    pgtype.Int4
	JoinedAt       pgtype.Timestamptz
}

type Game struct {
	ID                  int32
	Title               string
	Description         pgtype.Text
	GmUserID            int32
	State               pgtype.Text
	Genre               pgtype.Text
	StartDate           pgtype.Timestamptz
	EndDate             pgtype.Timestamptz
	RecruitmentDeadline pgtype.Timestamptz
	MaxPlayers          pgtype.Int4
	IsPublic            pgtype.Bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type GameApplication struct {
	ID               int32
	GameID           int32
	UserID           int32
	Role             string
	Message          pgtype.Text
	Status           pgtype.Text
	ReviewedByUserID pgtype.Int4
	ReviewedAt       pgtype.Timestamptz
	AppliedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type GameParticipant struct {
	ID       int32
	GameID   int32
	UserID   int32
	Role     string
	Status   pgtype.Text
	JoinedAt pgtype.Timestamptz
}

type GamePhase struct {
	ID          int32
	GameID      int32
	PhaseType   string
	PhaseNumber int32
	Title       string
	Description pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Deadline    pgtype.Timestamptz
	IsActive    pgtype.Bool
	CreatedAt   pgtype.Timestamptz
}

type Notification struct {
	ID                int32
	UserID            int32
	GameID            pgtype.Int4
	RelatedEntityType pgtype.Text
	RelatedEntityID   pgtype.Int4
	NotificationType  string
	Title             string
	Content           pgtype.Text
	IsRead            pgtype.Bool
	CreatedAt         pgtype.Timestamptz
}

type NpcAssignment struct {
	ID               int32
	CharacterID      int32
	AssignedUserID   int32
	AssignedByUserID int32
	AssignedAt       pgtype.Timestamptz
}

type PhaseTransition struct {
	ID          int32
	GameID      int32
	FromPhaseID pgtype.Int4
	ToPhaseID   int32
	InitiatedBy int32
	Reason      pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type PrivateMessage struct {
	ID                int32
	ConversationID    int32
	SenderUserID      pgtype.Int4
	SenderCharacterID pgtype.Int4
	Content           string
	SentAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type Session struct {
	ID      int32
	UserID  int32
	Data    string
	Expires pgtype.Timestamptz
}

type Thread struct {
	ID              int32
	GameID          int32
	PhaseID         pgtype.Int4
	Title           string
	Content         pgtype.Text
	CreatedByUserID int32
	IsPinned        pgtype.Bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ThreadPost struct {
	ID           int32
	ThreadID     int32
	ParentPostID pgtype.Int4
	UserID       int32
	CharacterID  pgtype.Int4
	Content      string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID                 int32
	Username           string
	Email              string
	Password           string
	IsAdmin            pgtype.Bool
	CreatedAt          pgtype.Timestamp
	DisplayName        pgtype.Text
	Bio                pgtype.Text
	Timezone           pgtype.Text
	EmailNotifications pgtype.Bool
	HighContrast       pgtype.Bool
}
