// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID      int32
	UserID  int32
	Data    string
	Expires pgtype.Timestamptz
}

type User struct {
	ID        int32
	Username  string
	Password  string
	Email     string
	CreatedAt pgtype.Timestamp
}
