// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, game_id, notification_type, title, content, related_entity_type, related_entity_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, game_id, related_entity_type, related_entity_id, notification_type, title, content, is_read, created_at
`

type CreateNotificationParams struct {
	UserID            int32       `json:"user_id"`
	GameID            pgtype.Int4 `json:"game_id"`
	NotificationType  string      `json:"notification_type"`
	Title             string      `json:"title"`
	Content           pgtype.Text `json:"content"`
	RelatedEntityType pgtype.Text `json:"related_entity_type"`
	RelatedEntityID   pgtype.Int4 `json:"related_entity_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.GameID,
		arg.NotificationType,
		arg.Title,
		arg.Content,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.NotificationType,
		&i.Title,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications)
	return err
}

const getGameNotifications = `-- name: GetGameNotifications :many
SELECT n.id, n.user_id, n.game_id, n.related_entity_type, n.related_entity_id, n.notification_type, n.title, n.content, n.is_read, n.created_at, u.username
FROM notifications n
JOIN users u ON n.user_id = u.id
WHERE n.game_id = $1
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type GetGameNotificationsParams struct {
	GameID pgtype.Int4 `json:"game_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetGameNotificationsRow struct {
	ID                int32              `json:"id"`
	UserID            int32              `json:"user_id"`
	GameID            pgtype.Int4        `json:"game_id"`
	RelatedEntityType pgtype.Text        `json:"related_entity_type"`
	RelatedEntityID   pgtype.Int4        `json:"related_entity_id"`
	NotificationType  string             `json:"notification_type"`
	Title             string             `json:"title"`
	Content           pgtype.Text        `json:"content"`
	IsRead            pgtype.Bool        `json:"is_read"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Username          string             `json:"username"`
}

func (q *Queries) GetGameNotifications(ctx context.Context, arg GetGameNotificationsParams) ([]GetGameNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getGameNotifications, arg.GameID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameNotificationsRow
	for rows.Next() {
		var i GetGameNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.NotificationType,
			&i.Title,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnreadNotifications = `-- name: GetUnreadNotifications :many
SELECT n.id, n.user_id, n.game_id, n.related_entity_type, n.related_entity_id, n.notification_type, n.title, n.content, n.is_read, n.created_at, g.title as game_title
FROM notifications n
LEFT JOIN games g ON n.game_id = g.id
WHERE n.user_id = $1 AND n.is_read = false
ORDER BY n.created_at DESC
`

type GetUnreadNotificationsRow struct {
	ID                int32              `json:"id"`
	UserID            int32              `json:"user_id"`
	GameID            pgtype.Int4        `json:"game_id"`
	RelatedEntityType pgtype.Text        `json:"related_entity_type"`
	RelatedEntityID   pgtype.Int4        `json:"related_entity_id"`
	NotificationType  string             `json:"notification_type"`
	Title             string             `json:"title"`
	Content           pgtype.Text        `json:"content"`
	IsRead            pgtype.Bool        `json:"is_read"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	GameTitle         pgtype.Text        `json:"game_title"`
}

func (q *Queries) GetUnreadNotifications(ctx context.Context, userID int32) ([]GetUnreadNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadNotificationsRow
	for rows.Next() {
		var i GetUnreadNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.NotificationType,
			&i.Title,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.GameTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT n.id, n.user_id, n.game_id, n.related_entity_type, n.related_entity_id, n.notification_type, n.title, n.content, n.is_read, n.created_at, g.title as game_title
FROM notifications n
LEFT JOIN games g ON n.game_id = g.id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserNotificationsParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUserNotificationsRow struct {
	ID                int32              `json:"id"`
	UserID            int32              `json:"user_id"`
	GameID            pgtype.Int4        `json:"game_id"`
	RelatedEntityType pgtype.Text        `json:"related_entity_type"`
	RelatedEntityID   pgtype.Int4        `json:"related_entity_id"`
	NotificationType  string             `json:"notification_type"`
	Title             string             `json:"title"`
	Content           pgtype.Text        `json:"content"`
	IsRead            pgtype.Bool        `json:"is_read"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	GameTitle         pgtype.Text        `json:"game_title"`
}

func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]GetUserNotificationsRow, error) {
	rows, err := q.db.Query(ctx, getUserNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNotificationsRow
	for rows.Next() {
		var i GetUserNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameID,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.NotificationType,
			&i.Title,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.GameTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markGameNotificationsRead = `-- name: MarkGameNotificationsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND game_id = $2
`

type MarkGameNotificationsReadParams struct {
	UserID int32       `json:"user_id"`
	GameID pgtype.Int4 `json:"game_id"`
}

func (q *Queries) MarkGameNotificationsRead(ctx context.Context, arg MarkGameNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markGameNotificationsRead, arg.UserID, arg.GameID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET is_read = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, game_id, related_entity_type, related_entity_id, notification_type, title, content, is_read, created_at
`

type MarkNotificationReadParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameID,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.NotificationType,
		&i.Title,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const notifyAudienceMembers = `-- name: NotifyAudienceMembers :exec
INSERT INTO notifications (user_id, game_id, notification_type, title, content, related_entity_type, related_entity_id)
SELECT gp.user_id, $1, $2, $3, $4, $5, $6
FROM game_participants gp
WHERE gp.game_id = $1 AND gp.role = 'audience' AND gp.status = 'active' AND gp.user_id != $7
`

type NotifyAudienceMembersParams struct {
	GameID            pgtype.Int4 `json:"game_id"`
	NotificationType  string      `json:"notification_type"`
	Title             string      `json:"title"`
	Content           pgtype.Text `json:"content"`
	RelatedEntityType pgtype.Text `json:"related_entity_type"`
	RelatedEntityID   pgtype.Int4 `json:"related_entity_id"`
	UserID            int32       `json:"user_id"`
}

func (q *Queries) NotifyAudienceMembers(ctx context.Context, arg NotifyAudienceMembersParams) error {
	_, err := q.db.Exec(ctx, notifyAudienceMembers,
		arg.GameID,
		arg.NotificationType,
		arg.Title,
		arg.Content,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
		arg.UserID,
	)
	return err
}

const notifyGM = `-- name: NotifyGM :exec
INSERT INTO notifications (user_id, game_id, notification_type, title, content, related_entity_type, related_entity_id)
SELECT g.gm_user_id, $1, $2, $3, $4, $5, $6
FROM games g
WHERE g.id = $1 AND g.gm_user_id != $7
`

type NotifyGMParams struct {
	GameID            pgtype.Int4 `json:"game_id"`
	NotificationType  string      `json:"notification_type"`
	Title             string      `json:"title"`
	Content           pgtype.Text `json:"content"`
	RelatedEntityType pgtype.Text `json:"related_entity_type"`
	RelatedEntityID   pgtype.Int4 `json:"related_entity_id"`
	GmUserID          int32       `json:"gm_user_id"`
}

func (q *Queries) NotifyGM(ctx context.Context, arg NotifyGMParams) error {
	_, err := q.db.Exec(ctx, notifyGM,
		arg.GameID,
		arg.NotificationType,
		arg.Title,
		arg.Content,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
		arg.GmUserID,
	)
	return err
}

const notifyGameParticipants = `-- name: NotifyGameParticipants :exec
INSERT INTO notifications (user_id, game_id, notification_type, title, content, related_entity_type, related_entity_id)
SELECT gp.user_id, $1, $2, $3, $4, $5, $6
FROM game_participants gp
WHERE gp.game_id = $1 AND gp.status = 'active' AND gp.user_id != $7
`

type NotifyGameParticipantsParams struct {
	GameID            pgtype.Int4 `json:"game_id"`
	NotificationType  string      `json:"notification_type"`
	Title             string      `json:"title"`
	Content           pgtype.Text `json:"content"`
	RelatedEntityType pgtype.Text `json:"related_entity_type"`
	RelatedEntityID   pgtype.Int4 `json:"related_entity_id"`
	UserID            int32       `json:"user_id"`
}

// Helper queries for creating notifications
func (q *Queries) NotifyGameParticipants(ctx context.Context, arg NotifyGameParticipantsParams) error {
	_, err := q.db.Exec(ctx, notifyGameParticipants,
		arg.GameID,
		arg.NotificationType,
		arg.Title,
		arg.Content,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
		arg.UserID,
	)
	return err
}
