// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: phases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activatePhase = `-- name: ActivatePhase :one
UPDATE game_phases
SET is_active = true
WHERE id = $1
RETURNING id, game_id, phase_type, phase_number, start_time, end_time, deadline, is_active, created_at
`

func (q *Queries) ActivatePhase(ctx context.Context, id int32) (GamePhase, error) {
	row := q.db.QueryRow(ctx, activatePhase, id)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createGamePhase = `-- name: CreateGamePhase :one
INSERT INTO game_phases (game_id, phase_type, phase_number, start_time, end_time, deadline)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, game_id, phase_type, phase_number, start_time, end_time, deadline, is_active, created_at
`

type CreateGamePhaseParams struct {
	GameID      int32
	PhaseType   string
	PhaseNumber int32
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Deadline    pgtype.Timestamptz
}

func (q *Queries) CreateGamePhase(ctx context.Context, arg CreateGamePhaseParams) (GamePhase, error) {
	row := q.db.QueryRow(ctx, createGamePhase,
		arg.GameID,
		arg.PhaseType,
		arg.PhaseNumber,
		arg.StartTime,
		arg.EndTime,
		arg.Deadline,
	)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAllGamePhases = `-- name: DeactivateAllGamePhases :exec
UPDATE game_phases
SET is_active = false
WHERE game_id = $1
`

func (q *Queries) DeactivateAllGamePhases(ctx context.Context, gameID int32) error {
	_, err := q.db.Exec(ctx, deactivateAllGamePhases, gameID)
	return err
}

const deactivatePhase = `-- name: DeactivatePhase :one
UPDATE game_phases
SET is_active = false, end_time = NOW()
WHERE id = $1
RETURNING id, game_id, phase_type, phase_number, start_time, end_time, deadline, is_active, created_at
`

func (q *Queries) DeactivatePhase(ctx context.Context, id int32) (GamePhase, error) {
	row := q.db.QueryRow(ctx, deactivatePhase, id)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAction = `-- name: DeleteAction :exec
DELETE FROM action_submissions
WHERE game_id = $1 AND user_id = $2 AND phase_id = $3
`

type DeleteActionParams struct {
	GameID  int32
	UserID  int32
	PhaseID int32
}

func (q *Queries) DeleteAction(ctx context.Context, arg DeleteActionParams) error {
	_, err := q.db.Exec(ctx, deleteAction, arg.GameID, arg.UserID, arg.PhaseID)
	return err
}

const getActivePhase = `-- name: GetActivePhase :one
SELECT id, game_id, phase_type, phase_number, start_time, end_time, deadline, is_active, created_at FROM game_phases
WHERE game_id = $1 AND is_active = true
`

func (q *Queries) GetActivePhase(ctx context.Context, gameID int32) (GamePhase, error) {
	row := q.db.QueryRow(ctx, getActivePhase, gameID)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getGameActions = `-- name: GetGameActions :many
SELECT acts.id, acts.game_id, acts.user_id, acts.phase_id, acts.character_id, acts.content, acts.submitted_at, acts.updated_at, u.username, c.name as character_name, gp.phase_type, gp.phase_number
FROM action_submissions acts
JOIN users u ON acts.user_id = u.id
JOIN game_phases gp ON acts.phase_id = gp.id
LEFT JOIN characters c ON acts.character_id = c.id
WHERE acts.game_id = $1
ORDER BY gp.phase_number, acts.submitted_at
`

type GetGameActionsRow struct {
	ID            int32
	GameID        int32
	UserID        int32
	PhaseID       int32
	CharacterID   pgtype.Int4
	Content       string
	SubmittedAt   pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Username      string
	CharacterName pgtype.Text
	PhaseType     string
	PhaseNumber   int32
}

func (q *Queries) GetGameActions(ctx context.Context, gameID int32) ([]GetGameActionsRow, error) {
	rows, err := q.db.Query(ctx, getGameActions, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameActionsRow
	for rows.Next() {
		var i GetGameActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.Content,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.CharacterName,
			&i.PhaseType,
			&i.PhaseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGamePhases = `-- name: GetGamePhases :many
SELECT id, game_id, phase_type, phase_number, start_time, end_time, deadline, is_active, created_at FROM game_phases
WHERE game_id = $1
ORDER BY phase_number
`

func (q *Queries) GetGamePhases(ctx context.Context, gameID int32) ([]GamePhase, error) {
	rows, err := q.db.Query(ctx, getGamePhases, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePhase
	for rows.Next() {
		var i GamePhase
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PhaseType,
			&i.PhaseNumber,
			&i.StartTime,
			&i.EndTime,
			&i.Deadline,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameResults = `-- name: GetGameResults :many
SELECT results.id, results.game_id, results.user_id, results.phase_id, results.gm_user_id, results.content, results.sent_at, u.username, gm.username as gm_username, gp.phase_type, gp.phase_number
FROM action_results results
JOIN users u ON results.user_id = u.id
JOIN users gm ON results.gm_user_id = gm.id
JOIN game_phases gp ON results.phase_id = gp.id
WHERE results.game_id = $1
ORDER BY gp.phase_number, results.sent_at
`

type GetGameResultsRow struct {
	ID          int32
	GameID      int32
	UserID      int32
	PhaseID     int32
	GmUserID    int32
	Content     string
	SentAt      pgtype.Timestamptz
	Username    string
	GmUsername  string
	PhaseType   string
	PhaseNumber int32
}

func (q *Queries) GetGameResults(ctx context.Context, gameID int32) ([]GetGameResultsRow, error) {
	rows, err := q.db.Query(ctx, getGameResults, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameResultsRow
	for rows.Next() {
		var i GetGameResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.GmUserID,
			&i.Content,
			&i.SentAt,
			&i.Username,
			&i.GmUsername,
			&i.PhaseType,
			&i.PhaseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestPhaseNumber = `-- name: GetLatestPhaseNumber :one
SELECT COALESCE(MAX(phase_number), 0)
FROM game_phases
WHERE game_id = $1
`

func (q *Queries) GetLatestPhaseNumber(ctx context.Context, gameID int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLatestPhaseNumber, gameID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getPhase = `-- name: GetPhase :one
SELECT id, game_id, phase_type, phase_number, start_time, end_time, deadline, is_active, created_at FROM game_phases WHERE id = $1
`

func (q *Queries) GetPhase(ctx context.Context, id int32) (GamePhase, error) {
	row := q.db.QueryRow(ctx, getPhase, id)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPhaseActions = `-- name: GetPhaseActions :many
SELECT acts.id, acts.game_id, acts.user_id, acts.phase_id, acts.character_id, acts.content, acts.submitted_at, acts.updated_at, u.username, c.name as character_name
FROM action_submissions acts
JOIN users u ON acts.user_id = u.id
LEFT JOIN characters c ON acts.character_id = c.id
WHERE acts.phase_id = $1
ORDER BY acts.submitted_at
`

type GetPhaseActionsRow struct {
	ID            int32
	GameID        int32
	UserID        int32
	PhaseID       int32
	CharacterID   pgtype.Int4
	Content       string
	SubmittedAt   pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Username      string
	CharacterName pgtype.Text
}

func (q *Queries) GetPhaseActions(ctx context.Context, phaseID int32) ([]GetPhaseActionsRow, error) {
	rows, err := q.db.Query(ctx, getPhaseActions, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhaseActionsRow
	for rows.Next() {
		var i GetPhaseActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.Content,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.CharacterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhaseResults = `-- name: GetPhaseResults :many
SELECT results.id, results.game_id, results.user_id, results.phase_id, results.gm_user_id, results.content, results.sent_at, u.username, gm.username as gm_username
FROM action_results results
JOIN users u ON results.user_id = u.id
JOIN users gm ON results.gm_user_id = gm.id
WHERE results.phase_id = $1
ORDER BY results.sent_at
`

type GetPhaseResultsRow struct {
	ID         int32
	GameID     int32
	UserID     int32
	PhaseID    int32
	GmUserID   int32
	Content    string
	SentAt     pgtype.Timestamptz
	Username   string
	GmUsername string
}

func (q *Queries) GetPhaseResults(ctx context.Context, phaseID int32) ([]GetPhaseResultsRow, error) {
	rows, err := q.db.Query(ctx, getPhaseResults, phaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhaseResultsRow
	for rows.Next() {
		var i GetPhaseResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.GmUserID,
			&i.Content,
			&i.SentAt,
			&i.Username,
			&i.GmUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAction = `-- name: GetUserAction :one
SELECT id, game_id, user_id, phase_id, character_id, content, submitted_at, updated_at FROM action_submissions
WHERE game_id = $1 AND user_id = $2 AND phase_id = $3
`

type GetUserActionParams struct {
	GameID  int32
	UserID  int32
	PhaseID int32
}

func (q *Queries) GetUserAction(ctx context.Context, arg GetUserActionParams) (ActionSubmission, error) {
	row := q.db.QueryRow(ctx, getUserAction, arg.GameID, arg.UserID, arg.PhaseID)
	var i ActionSubmission
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.Content,
		&i.SubmittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserActions = `-- name: GetUserActions :many
SELECT acts.id, acts.game_id, acts.user_id, acts.phase_id, acts.character_id, acts.content, acts.submitted_at, acts.updated_at, gp.phase_type, gp.phase_number
FROM action_submissions acts
JOIN game_phases gp ON acts.phase_id = gp.id
WHERE acts.game_id = $1 AND acts.user_id = $2
ORDER BY gp.phase_number DESC
`

type GetUserActionsParams struct {
	GameID int32
	UserID int32
}

type GetUserActionsRow struct {
	ID          int32
	GameID      int32
	UserID      int32
	PhaseID     int32
	CharacterID pgtype.Int4
	Content     string
	SubmittedAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	PhaseType   string
	PhaseNumber int32
}

func (q *Queries) GetUserActions(ctx context.Context, arg GetUserActionsParams) ([]GetUserActionsRow, error) {
	rows, err := q.db.Query(ctx, getUserActions, arg.GameID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserActionsRow
	for rows.Next() {
		var i GetUserActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.CharacterID,
			&i.Content,
			&i.SubmittedAt,
			&i.UpdatedAt,
			&i.PhaseType,
			&i.PhaseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserResults = `-- name: GetUserResults :many
SELECT results.id, results.game_id, results.user_id, results.phase_id, results.gm_user_id, results.content, results.sent_at, gp.phase_type, gp.phase_number, u.username as gm_username
FROM action_results results
JOIN game_phases gp ON results.phase_id = gp.id
JOIN users u ON results.gm_user_id = u.id
WHERE results.game_id = $1 AND results.user_id = $2
ORDER BY gp.phase_number DESC
`

type GetUserResultsParams struct {
	GameID int32
	UserID int32
}

type GetUserResultsRow struct {
	ID          int32
	GameID      int32
	UserID      int32
	PhaseID     int32
	GmUserID    int32
	Content     string
	SentAt      pgtype.Timestamptz
	PhaseType   string
	PhaseNumber int32
	GmUsername  string
}

func (q *Queries) GetUserResults(ctx context.Context, arg GetUserResultsParams) ([]GetUserResultsRow, error) {
	rows, err := q.db.Query(ctx, getUserResults, arg.GameID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserResultsRow
	for rows.Next() {
		var i GetUserResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.PhaseID,
			&i.GmUserID,
			&i.Content,
			&i.SentAt,
			&i.PhaseType,
			&i.PhaseNumber,
			&i.GmUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendActionResult = `-- name: SendActionResult :one
INSERT INTO action_results (game_id, user_id, phase_id, gm_user_id, content)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, game_id, user_id, phase_id, gm_user_id, content, sent_at
`

type SendActionResultParams struct {
	GameID   int32
	UserID   int32
	PhaseID  int32
	GmUserID int32
	Content  string
}

func (q *Queries) SendActionResult(ctx context.Context, arg SendActionResultParams) (ActionResult, error) {
	row := q.db.QueryRow(ctx, sendActionResult,
		arg.GameID,
		arg.UserID,
		arg.PhaseID,
		arg.GmUserID,
		arg.Content,
	)
	var i ActionResult
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.GmUserID,
		&i.Content,
		&i.SentAt,
	)
	return i, err
}

const submitAction = `-- name: SubmitAction :one
INSERT INTO action_submissions (game_id, user_id, phase_id, character_id, content)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (game_id, user_id, phase_id)
DO UPDATE SET content = $5, character_id = $4, updated_at = NOW()
RETURNING id, game_id, user_id, phase_id, character_id, content, submitted_at, updated_at
`

type SubmitActionParams struct {
	GameID      int32
	UserID      int32
	PhaseID     int32
	CharacterID pgtype.Int4
	Content     string
}

func (q *Queries) SubmitAction(ctx context.Context, arg SubmitActionParams) (ActionSubmission, error) {
	row := q.db.QueryRow(ctx, submitAction,
		arg.GameID,
		arg.UserID,
		arg.PhaseID,
		arg.CharacterID,
		arg.Content,
	)
	var i ActionSubmission
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.PhaseID,
		&i.CharacterID,
		&i.Content,
		&i.SubmittedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhaseDeadline = `-- name: UpdatePhaseDeadline :one
UPDATE game_phases
SET deadline = $2
WHERE id = $1
RETURNING id, game_id, phase_type, phase_number, start_time, end_time, deadline, is_active, created_at
`

type UpdatePhaseDeadlineParams struct {
	ID       int32
	Deadline pgtype.Timestamptz
}

func (q *Queries) UpdatePhaseDeadline(ctx context.Context, arg UpdatePhaseDeadlineParams) (GamePhase, error) {
	row := q.db.QueryRow(ctx, updatePhaseDeadline, arg.ID, arg.Deadline)
	var i GamePhase
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PhaseType,
		&i.PhaseNumber,
		&i.StartTime,
		&i.EndTime,
		&i.Deadline,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
