// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, data, expires
) VALUES (
             $1, $2, $3
         )
RETURNING id, user_id, data, expires
`

type CreateSessionParams struct {
	UserID  int32              `json:"user_id"`
	Data    string             `json:"data"`
	Expires pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.Data, arg.Expires)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.Expires,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions
WHERE data = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, data string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, data)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions
WHERE user_id = $1
`

// Invalidate all sessions for a user (used when banning)
func (q *Queries) DeleteUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, data, expires FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id int32) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.Expires,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, user_id, data, expires FROM sessions
WHERE data = $1 LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, data string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, data)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Data,
		&i.Expires,
	)
	return i, err
}

const getSessionsByUser = `-- name: GetSessionsByUser :many
SELECT id, user_id, data, expires FROM sessions
WHERE user_id = $1 AND expires > NOW()
`

func (q *Queries) GetSessionsByUser(ctx context.Context, userID int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Data,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionToken = `-- name: UpdateSessionToken :exec
UPDATE sessions
SET data = $2
WHERE id = $1
`

type UpdateSessionTokenParams struct {
	ID   int32  `json:"id"`
	Data string `json:"data"`
}

func (q *Queries) UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, updateSessionToken, arg.ID, arg.Data)
	return err
}
