// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :exec

UPDATE users
SET is_banned = TRUE,
    banned_at = NOW(),
    banned_by_user_id = $2
WHERE id = $1
`

type BanUserParams struct {
	ID             int32       `json:"id"`
	BannedByUserID pgtype.Int4 `json:"banned_by_user_id"`
}

// User banning queries
func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser, arg.ID, arg.BannedByUserID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, password, email
) VALUES (
             $1, $2, $3
         )
RETURNING id, username, email, password, is_admin, created_at, display_name, bio, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedByUserID,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, is_admin, created_at, display_name, bio, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedByUserID,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, is_admin, created_at, display_name, bio, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
		&i.IsBanned,
		&i.BannedAt,
		&i.BannedByUserID,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, email, created_at
FROM users
WHERE is_admin = TRUE
ORDER BY created_at ASC
`

type ListAdminsRow struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListAdmins(ctx context.Context) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminsRow
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBannedUsers = `-- name: ListBannedUsers :many
SELECT u.id, u.username, u.email, u.banned_at, u.banned_by_user_id, u.created_at,
       admin.username as banned_by_username
FROM users u
LEFT JOIN users admin ON u.banned_by_user_id = admin.id
WHERE u.is_banned = TRUE
ORDER BY u.banned_at DESC
`

type ListBannedUsersRow struct {
	ID               int32            `json:"id"`
	Username         string           `json:"username"`
	Email            string           `json:"email"`
	BannedAt         pgtype.Timestamp `json:"banned_at"`
	BannedByUserID   pgtype.Int4      `json:"banned_by_user_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	BannedByUsername pgtype.Text      `json:"banned_by_username"`
}

func (q *Queries) ListBannedUsers(ctx context.Context) ([]ListBannedUsersRow, error) {
	rows, err := q.db.Query(ctx, listBannedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBannedUsersRow
	for rows.Next() {
		var i ListBannedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.BannedAt,
			&i.BannedByUserID,
			&i.CreatedAt,
			&i.BannedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password, is_admin, created_at, display_name, bio, timezone, email_notifications, high_contrast, is_banned, banned_at, banned_by_user_id FROM users
ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Bio,
			&i.Timezone,
			&i.EmailNotifications,
			&i.HighContrast,
			&i.IsBanned,
			&i.BannedAt,
			&i.BannedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users
SET is_banned = FALSE,
    banned_at = NULL,
    banned_by_user_id = NULL
WHERE id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, unbanUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
set username = $2,
    password = $3,
    email = $4
WHERE id = $1
`

type UpdateUserParams struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Email,
	)
	return err
}

const updateUserAdminStatus = `-- name: UpdateUserAdminStatus :exec

UPDATE users
SET is_admin = $2
WHERE id = $1
`

type UpdateUserAdminStatusParams struct {
	ID      int32       `json:"id"`
	IsAdmin pgtype.Bool `json:"is_admin"`
}

// Admin management queries
func (q *Queries) UpdateUserAdminStatus(ctx context.Context, arg UpdateUserAdminStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserAdminStatus, arg.ID, arg.IsAdmin)
	return err
}
