// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, password, email
) VALUES (
             $1, $2, $3
         )
RETURNING id, username, email, password, is_admin, created_at, display_name, bio, timezone, email_notifications, high_contrast
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, is_admin, created_at, display_name, bio, timezone, email_notifications, high_contrast FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, is_admin, created_at, display_name, bio, timezone, email_notifications, high_contrast FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.Timezone,
		&i.EmailNotifications,
		&i.HighContrast,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password, is_admin, created_at, display_name, bio, timezone, email_notifications, high_contrast FROM users
ORDER BY username
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Bio,
			&i.Timezone,
			&i.EmailNotifications,
			&i.HighContrast,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
set username = $2,
    password = $3,
    email = $4
WHERE id = $1
`

type UpdateUserParams struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Email,
	)
	return err
}
